-- SQL Migration for Uploading Restaurant Menus
-- You can copy and paste the content of this file into your Supabase SQL Editor.

-- Step 1: Add 'subcategory' column to 'menus' table if it doesn't exist.
DO $$
BEGIN
  IF NOT EXISTS(SELECT *
    FROM information_schema.columns
    WHERE table_name='menus' and column_name='subcategory')
  THEN
      ALTER TABLE "public"."menus" ADD COLUMN "subcategory" text;
  END IF;
END $$;

-- Step 2: Clear existing menu items for the restaurants to avoid duplicates.
DELETE FROM public.menus
WHERE bar_id IN (
  SELECT id FROM public.bars WHERE name IN (
    'The Londoner British Pub Sliema',
    'Mamma Mia',
    'The Brew Bar Grill'
  )
);

-- Step 3: Insert the new menu items.
INSERT INTO public.menus (bar_id, name, description, price, category, subcategory, is_available) VALUES
-- The Londoner British Pub Sliema
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Vegetable Spring Rolls (V)', 'Served with sweet chilli dip', 7.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Meat Balls', 'Beef and pork mince balls with jus', 9.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Fish Cod Goujons', 'Served with lemon mayonnaise', 9.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Chicken Satay Skewers', 'Served with peanut sauce dip', 10.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Southern Fried Chicken Strips', 'Served with red white dip', 10.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Mini Angus Cheese Burgers (4 Pieces)', NULL, 12.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Traditional Nachos (V)', 'Cheese sauce, jalapeño, tomato salsa', 12.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Deep Fried Calamari', 'Breaded, served with tartar sauce and lemon wedge', 14.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Chicken & Spianata Nachos', 'Diced chicken, onions, salami spianata, nacho cheese sauce', 15.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Grilled Lamb Kofta', 'Served with yoghurt mint dip', 10.95, 'Food', 'STARTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Ultimate Garlic Bread (V)', 'Soft tear and share buns with garlic butter', 6.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Ultimate Garlic Bread with Cheese (V)', 'Soft tear and share buns with garlic butter and cheese', 7.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Proper Stealth Fries (V)', NULL, 5.5, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cheese Stealth Fries (V) (H)', 'Served with curry ketchup', 5.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Beer Battered Onion Rings (V)', 'Served with spicy mayo', 8.5, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Spicy Pork Sausages', NULL, 7.5, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Fish Cod Bites', 'Served with tartar sauce', 9.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Fish Popcorn', 'Served with curry ketchup', 9.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Crispy Chicken Wings', 'Served with sweet chilli dip', 11.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Camembert Cheese Bites', NULL, 9.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Traditional Focaccia (V)', 'Cherry tomatoes, black olives, rosemary, and olive oil', 9.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cheesy Bruschetta (V)', 'Tomatoes, garlic, basil, and melted cheese', 6.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Bruschetta (V)', 'Tomatoes, garlic, and basil', 5.95, 'Food', 'NIBBLES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Royal Chicken Caesar', 'Grilled chicken, lettuce, bacon, parmesan, croutons, tomatoes, caesar dressing', 15.95, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Royal Salmon Caesar', 'Oven baked salmon fillet, ricotta, lettuce, cucumbers, onions, peppers, black olives, parmesan, croutons, tomatoes, caesar dressing', 17.95, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'West End Oriental Platter', '4 pork ribs, meatballs, 2 vegetable spring rolls, fish bites, 2 lamb koftas, 4 chicken wings, fish popcorn, 2 chicken satays, stealth fries, garlic bread, and dips', 39.95, 'Food', 'PLATTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Seafood & Fish Platter', 'Fish bites, deep fried calamari, fish popcorn, scampi, Londoner fish & chips, garlic bread, and dips', 39.95, 'Food', 'PLATTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Drinker''s Favourite', '2 mini beef burgers, 2 lamb koftas, 4 chicken wings, spiced honey pork sausages, 2 chicken strips, 4 pork ribs, meatballs, garlic bread, 4 onion rings, and stealth fries smothered in melted cheese', 42.95, 'Food', 'PLATTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cold Cuts & Cheese Platter', 'Selection of Italian cold cuts and British cheeses, served with olives, mixed fruit & nuts, water biscuits, and grissini', 32.95, 'Food', 'PLATTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'The Londoner Fish & Chips', 'Beer battered cod, mushy peas, tartar sauce & stealth fries', 19.95, 'Food', 'FISH & CHIPS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Londoner Hot Dog', 'Grilled frankfurter, crispy onions, melted cheese, Heinz baked beans, and stealth fries', 12.95, 'Food', 'HOT DOG', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Bangers & Mash', 'Cumberland sausages, mashed potatoes, and onion gravy', 14.95, 'Food', 'CLASSICS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Half Roast Chicken in a Basket', 'Served with gravy and stealth fries', 16.95, 'Food', 'CLASSICS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Chicken Tikka Masala (H)', 'Served with basmati rice and pita bread', 16.95, 'Food', 'CLASSICS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Oven Baked Salmon Fillet', 'Served with mashed potatoes, fresh vegetables, and tarragon sauce', 23.95, 'Food', 'CLASSICS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Baked Potato Gnocchi', 'Creamy dolcelatte cheese sauce, walnuts, red Leicester, and melted cheddar cheese', 13.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Garganelli Chicken Tartufo', 'Chicken, mushrooms, spring onions, garlic, white wine, and truffle cream', 15.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Garganelli Beef Porcini', 'Beef chunks, porcini mushrooms, red wine, garlic, spring onions, jus, cream, and grana shavings', 15.95, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Strozzapreti Salmon', 'Fresh salmon, garlic, spring onions, cherry tomatoes, Pernod, cream, and tomato sauce', 15.95, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Tortellini in Puff Pastry', 'Meat tortellini, onions, garlic, Portobello mushrooms, bacon, white wine, and cream', 14.95, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Miss Chicken Classy', 'Grilled chicken breast, camembert cheese, bacon, and mango chutney', 16.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'The Londoner', 'Angus beef, cheese, lettuce, tomatoes, and fried onions', 16.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'The Big Crusty', 'Angus beef patty, fried crusty cheese, bacon, onion chutney, Branston pickles, and BBQ sauce', 17.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Sir Wellington', 'Angus beef patty, Portobello mushrooms, BBQ sauce, Branston pickles, smoked cheese, and onion chutney', 17.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Westie Burger', 'Angus beef patty, smoked cheese, crunchy peanut butter, bacon, fried onions, maple syrup, lettuce, and tomato', 17.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'The Big Ben', 'Angus beef patty, deep fried chicken fillet, fried crusty cheese, crispy bacon, onion chutney, and BBQ sauce', 19.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Breaded Chicken Burger', 'Shallow fried breaded chicken fillets, smoked cheese, lettuce, tomatoes, and curry ketchup', 15.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'The Veggie (V)', 'A mixture of onions, carrots, sweetcorn, broccoli, mashed potato & crispy coating', 11.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), '280g Fresh Grilled Chicken Breast', 'Served with seasonal vegetables and stealth fries', 19.95, 'Food', 'GRILLS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Rack of Sticky Pork Loin Ribs', 'Southern honey and Jack Daniels sauce with stealth fries', 17.95, 'Food', 'GRILLS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'The King''s Beef Tagliata', '300g Beef flank steak, rucola, parmesan shavings, baby potatoes, and cherry tomatoes', 27.95, 'Food', 'GRILLS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Fresh Pure Angus Rib Eye', '300g Grilled steak, seasonal vegetables, and stealth fries', 29.95, 'Food', 'GRILLS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Chicken, Mushroom & Bacon Pie', 'Smoked bacon, chicken velouté, chicken breast, and mushrooms', 14.95, 'Food', 'PIES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Steak & Guinness Pie', 'Beef chunks, Guinness ale, root vegetables, and gravy', 14.95, 'Food', 'PIES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Shepherd's Pie', 'Slow cooked lamb mince, mashed potatoes, and side salad', 14.95, 'Food', 'PIES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Chicken Nuggets & Chips', NULL, 10.95, 'Food', 'KIDS MENU', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Penne with Tomato Sauce', NULL, 9.95, 'Food', 'KIDS MENU', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Hot Dog, Chips & Baked Beans', NULL, 9.95, 'Food', 'KIDS MENU', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Fish & Chips', NULL, 12.95, 'Food', 'KIDS MENU', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Burger & Chips', NULL, 12.95, 'Food', 'KIDS MENU', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Snickers', 'Oven caramelized chocolate cream, roasted peanuts, and nutty chocolate', 6.5, 'Food', 'DESSERTS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Oreo', 'Dark crunchy biscuits with milky white chocolate mousse', 6.5, 'Food', 'DESSERTS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Nutella Tart', 'Served with panna', 6.5, 'Food', 'DESSERTS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Apple Crumble', 'Served with warm custard', 6.5, 'Food', 'DESSERTS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Alison''s Soft Baked Milk Chocolate Cookie', NULL, 6.95, 'Food', 'DESSERTS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Panna Small Still Water', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'San Pellegrino Small', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Coca Cola (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Coke Zero (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Kinnie (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Diet Kinnie (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Sprite (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Sprite Zero (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Fanta (330ml)', NULL, 2.6, 'Drinks', 'COLD BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cisk Lager (330ml)', NULL, 3.05, 'Drinks', 'BEERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cisk Excel (330ml)', NULL, 3.05, 'Drinks', 'BEERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cisk Chill Lemon (330ml)', NULL, 3.05, 'Drinks', 'BEERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Cisk Chill Berry (330ml)', NULL, 3.05, 'Drinks', 'BEERS', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Donato Chardonnay', NULL, 15.95, 'Drinks', 'WHITE WINES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Glicine Corvo', NULL, 20.95, 'Drinks', 'WHITE WINES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Gavi Di Gavi', NULL, 24.5, 'Drinks', 'WHITE WINES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Marenzio Merlot', NULL, 15.95, 'Drinks', 'RED WINES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Valpolicella Classico DOC', NULL, 18.95, 'Drinks', 'RED WINES', true),
((SELECT id FROM public.bars WHERE name = 'The Londoner British Pub Sliema'), 'Malbec', NULL, 21.95, 'Drinks', 'RED WINES', true),

-- Mamma Mia
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Chicken Dippers', 'Homemade breaded chicken tenderloins with coleslaw, fries, honey cajun mayo, and BBQ sauce', 18.5, 'Food', 'RIBS & DIPPERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Barbeque Ribs', 'Pork ribs with BBQ sauce, coleslaw, and fries', 26.5, 'Food', 'RIBS & DIPPERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Half Barbeque Ribs', 'Half rack pork ribs with BBQ sauce, coleslaw, and fries', 22.5, 'Food', 'RIBS & DIPPERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Tennessee Ribs', 'Pork ribs with American sauce, coleslaw, and fries', 26.5, 'Food', 'RIBS & DIPPERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Half Tennessee Ribs', 'Half rack pork ribs with BBQ sauce, coleslaw, and fries', 22.5, 'Food', 'RIBS & DIPPERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Prosciutto & Buffalo Salad', 'Prosciutto and mozzarella di bufala on lettuce, rucola, pistachios, fresh peach, citrus vinaigrette', 15.5, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Quinoa Salad (Avocado & Prawns)', 'Quinoa, prawns, avocado, tomatoes, cucumber, carrots, misticanza', 16.5, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Greek Chicken Salad', 'Marinated boneless chicken thighs, greens, couscous, chickpeas, cucumber, feta, onions, peppers, cherry tomatoes, olives, yogurt tzatziki dressing', 16.5, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Chicken Caesar Salad', 'Greens, tomatoes, olives, grana cheese, croutons, grilled chicken, creamy Caesar dressing', 16.5, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Fresh Salmon Salad', 'Pan seared salmon fillet with orange and ginger marination on lettuce', 18.95, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Penne Cajun', 'Chicken, Cajun spices, herbs, onions, mushrooms, cream', 16.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Chicken Pancetta Rice', 'Chicken, pancetta, mushrooms, onions, Parmesan, sundried tomatoes, white wine, cream', 16.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Curry Rice', 'Chicken, curry spices, dried fruit, leeks, coconut cream', 16.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Spaghetti Rabbit', 'Rabbit, onions, garlic, thyme, peas, red wine, tomato sauce', 16.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Fusilli Salsiccia', 'Maltese sausage ragu, herbs, sundried tomatoes, cream, pecorino pepato cheese', 16.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Penne Zarina', 'Smoked salmon, garlic, onions, tomatoes, herbs, caviar, cream', 16.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Linguine Fillet', 'Beef fillet strips, mushrooms, porcini, onions, garlic, white wine, cream', 18.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Linguine Nettuno', 'Calamari, prawns, garlic, onions, Pernod, prawn bisque, cream', 18.5, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Linguine Octopus', 'Octopus, garlic, herbs, white wine, tomato sauce', 18.95, 'Food', 'PASTA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Rabbit', 'Pan fried rabbit with garlic, spring onions, white wine, rabbit jus, fries', 24, 'Food', 'MAINS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Boneless Half Chicken', 'Charcoal grilled boneless chicken, hummus dip, fries', 20.95, 'Food', 'MAINS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Tarragon Chicken', 'Chicken breast, mushrooms, onions, brandy, tarragon, cream, lemon, salad, fries', 24, 'Food', 'MAINS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Baked Salmon', 'Salmon fillet, sundried tomato & herb crust, spinach, prawn sauce, fries', 25.95, 'Food', 'MAINS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Octopus', 'Pan fried octopus with garlic, herbs, salad, fries', 27.95, 'Food', 'MAINS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Lady Steak (Tagliata, 350g)', 'Char grilled beef skirt, rucola, parmesan, fries, port wine jus', 28, 'Food', 'MEAT', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Ribeye Steak (350g)', 'Black Angus ribeye, charcoal grilled, fries, salad', 31, 'Food', 'MEAT', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Fillet Chef', 'Prime fillet steak, charcoal grilled, mushrooms, onions, pancetta, cream, salad, fries', 32, 'Food', 'MEAT', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Fillet Peppered', 'Prime fillet steak, charcoal grilled, crushed peppercorns, cream, salad, fries', 32, 'Food', 'MEAT', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'American Beef Burger', 'Double beef patties, lettuce, tomatoes, gherkins, fried onions, pancetta, cheddar, special sauce, fries', 16.9, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Mexican Beef Burger', 'Double beef patties, guacamole, bean & pancetta ragu', 16.9, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Margherita', 'Tomatoes, mozzarella fior di latte, oregano', 12, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Margherita Di Bufola', 'Tomatoes, mozzarella di bufala, basil, olive oil, oregano', 14.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Mortadella Pizza', 'Pistachio pesto, mozzarella fior di latte, mortadella, pistachio granules', 14.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Capricciosa', 'Tomatoes, mozzarella fior di latte, mushrooms, ham, eggs, olives, artichoke hearts, oregano', 15, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Pepperoni', 'Yellow tomato sauce, mozzarella fior di latte, pepperoni, oregano', 14.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Vegan Pizza', 'Cream of marrow, aubergine, porcini, fried marrows, vegan mozzarella, cherry tomatoes, oregano', 16.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'BBQ Chicken Pizza', 'Tomatoes, mozzarella fior di latte, chicken, peppers, porcini, BBQ sauce', 16.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Holy Smok N'' Ribs', 'Tomatoes, provolone, jalapeño, boneless ribs, guanciale, caramelized onions, BBQ sauce', 16.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Meat Lover Pizza', 'Tomato sauce, provolone, ribeye, sausages, peppers, onions, yogurt drizzle', 17.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Gamberetti Pizza', 'Cream of marrow, fried marrows, prawns, stracciatella cheese, peperoncino, lemon zest', 17.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Tre Colore Focaccia', 'Mozzarella di bufala, cherry tomatoes, prosciutto, rucola, grana shavings', 16.5, 'Food', 'PIZZA', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Pepper Sauce', NULL, 3.95, 'Food', 'EXTRAS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Chef Sauce', NULL, 3.95, 'Food', 'EXTRAS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'BBQ Sauce', NULL, 3.95, 'Food', 'EXTRAS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Tennessee Sauce', NULL, 2.5, 'Food', 'EXTRAS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Cajun Sauce', NULL, 2.5, 'Food', 'EXTRAS', true),
((SELECT id FROM public.bars WHERE name = 'Mamma Mia'), 'Fries', NULL, 3.5, 'Food', 'EXTRAS', true),

-- The Brew Bar Grill
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Tres Tacos', '3 mini tortillas with chicken, beef, or fish, topped with pico de gallo, salsa hot sauce & sour cream', 16, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Quesadilla', 'Folded tortilla filled with chicken or beef, salsa, or mozzarella', 15, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Nachos', 'Crispy nachos topped with beef, pico de gallo, pickled jalapeños, melted cheese, guacamole', 15, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Chicken Wings (400g)', 'Jack Daniel''s BBQ, Buffalo, or Honey Mustard sauce with a dip', 12, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Mozzarella Sticks', '8 breaded mozzarella sticks with honey mustard dip', 10, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Large Fries', NULL, 7, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Crispy Fried Sardines', NULL, 12, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Fried Salty Smelt Fish', NULL, 12, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Cheesy Chips', 'Slightly spicy', 8.5, 'Food', 'APPETIZERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'The Brew Platter', 'Half rack ribs, chicken wings, mixed sausages, beer battered onion rings, salad, fries, honey mustard', 39.95, 'Food', 'PLATTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'The Big Chicken Wing Platter', '2400g of chicken wings in 4 sauces: honey garlic, Jack Daniel''s BBQ, honey mustard, buffalo sauce', 39, 'Food', 'PLATTERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Caesar Salad', 'Lettuce, tomatoes, croutons, Grana cheese, chicken breast, crispy bacon, Caesar dressing', 17.95, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Green Salad', 'Mixed lettuce, olives, onions, peppers, cherry tomatoes, feta cheese, basil flavored oil', 11.95, 'Food', 'SALADS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Veggie Burger', 'Breaded veggie patty, red Leicester cheese, lettuce in basil oil, tomatoes, brioche bun', 12.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Chicken Caesar Burger', 'Breaded fresh chicken breast patty, lettuce, tomatoes, crushed croutons, Grana cheese, Caesar dressing', 13.9, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Pork Rib Burger', 'BBQ sauce, chopped onions, slow cooked pork rib (200g), tomato, homemade roast potatoes', 16.95, 'Food', 'BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Steakhouse Burger', '200g beef patty, crispy bacon, red Leicester cheese, crispy onions, tomatoes, coleslaw, Jack Daniel''s BBQ sauce, brioche bun', 16.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Picke My Funny Bone Burger', '200g beef patty, cheddar cheese, fried pickles, lettuce, Jay''s burger juice, brioche bun', 15.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Royal with Cheese', '200g beef patty, cheddar, ketchup, mustard, pickles, chopped onion, sesame seed bun', 15.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'The Godfather', '200g beef patty, mozzarella di bufala, pistachios, rucola, pesto, brioche bun', 16.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Django', '200g beef patty, pico de gallo, Mexican cheese, spicy chorizo, Mexicana sauce, brioche bun, house guacamole', 16.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'The American Classic', '200g beef patty, crispy bacon, cheddar cheese, tomatoes, pickles, Jay''s burger juice, sesame seed bun', 15.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'The Brew Truffle Burger', '200g beef patty, fresh Italian truffle, homemade truffle mayo, cheddar cheese, tomatoes, lettuce', 20.95, 'Food', 'DRY AGED BEEF BURGERS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Juicy Ribs', 'Honey mustard sauce (cooked in golden ale beer) or Jack Daniel''s BBQ sauce with beer battered onion rings', 18, 'Food', 'GRILL', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Rib Eye Steak (350g)', 'Recommended with pepper sauce and steakhouse potatoes', 33, 'Food', 'GRILL', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Grilled Chicken Breast', 'Served with side dishes of your choice', 18, 'Food', 'GRILL', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Pork Schnitzel (400g)', NULL, 21, 'Food', 'GRILL', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Grilled Sticky Ribs', 'Price per 100g', 15, 'Food', 'GRILL', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'One Meter Ribs', 'One meter rack with sauce of choice, beer battered onion rings', 59, 'Food', 'HOUSE SPECIALS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Sausage Mix', '400g Bavarian, Maltese, and spicy sausage', 18, 'Food', 'HOUSE SPECIALS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Inferno Wings (6 pcs)', 'Spicy chicken wings', 12, 'Food', 'HOUSE SPECIALS', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Grilled Salmon', 'Served with side dishes of your choice', 22, 'Food', 'SEAFOOD', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Coca Cola (250ml)', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Coca Cola Zero (250ml)', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Fanta (250ml)', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Sprite (250ml)', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Still Water', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Sparkling Water', NULL, 2.1, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Ice Tea Lemon', NULL, 3.05, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Ice Tea Peach', NULL, 3.05, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Tonic Water', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Bitter Lemon', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Ginger Ale', NULL, 2.85, 'Drinks', 'BEVERAGES', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Pilsner (1L)', '5.2% vol', 9, 'Drinks', 'HOMEMADE BEER', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Pilsner (2L)', '5.2% vol', 17, 'Drinks', 'HOMEMADE BEER', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Valletta 2018 (1L)', '4.8% vol', 9, 'Drinks', 'HOMEMADE BEER', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Valletta 2018 (2L)', '4.8% vol', 17, 'Drinks', 'HOMEMADE BEER', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Golden Ale (1L)', '6% vol', 9, 'Drinks', 'HOMEMADE BEER', true),
((SELECT id FROM public.bars WHERE name = 'The Brew Bar Grill'), 'Golden Ale (2L)', '6% vol', 17, 'Drinks', 'HOMEMADE BEER', true); 