name: CI & Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Unit / smoke tests
        run: |
          if [ -f package.json ] && npm run | grep -q "test"; then npm test; else echo "No tests"; fi

  migrate-build-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    # environment: production  # uncomment if GitHub environment configured
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Supabase CLI setup
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase db diff --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --from-local || true
          supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password $SUPABASE_DB_PASSWORD

      - name: Build Vite site
        run: npm run build

      - name: Deploy to Production (Cloudflare Pages example)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: icupa-pwa
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Post-deploy health check
        run: |
          curl -sSf https://icupa.example.com/ || exit 1
          curl -sSf https://nireplgrlwhwppjtfxbb.supabase.co/rest/v1/ || exit 1 