name: Cursor Code Review

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - develop

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Cursor Review
        uses: getcursor/cursor-review@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .cursor/config.yaml
          fail-on-error: false
