name: Cursor Guard

on:
  push:
    branches:
      - main
      - lovable/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Cursor robot
        run: npx --yes @trycursor/cli@latest review \
             --openai-key ${{ secrets.OPENAI_API_KEY }}

      - name: Commit Cursor fixes
        run: |
          git config user.name  "Cursor Bot"
          git config user.email "cursor-bot@example.com"
          git diff --quiet || (git commit -am "chore(cursor): auto-fixes" && git push)
