name: Cursor Guard

on:
  push:
    branches:
      - main
      - lovable/**

permissions:
  contents: write
  actions: read

jobs:
  check:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Cursor review
        uses: trycursor/action-docker@v1
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit Cursor fixes
        run: |
          git config user.name  "Cursor Bot"
          git config user.email "cursor-bot@example.com"
          git diff --quiet || (git commit -am "chore(cursor): auto-fixes" && git push)
