name: CI Quality Check

on:
  push:
    branches:
      - main
      - lovable/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run build

      - name: Run linting (non-blocking)
        run: npm run lint || echo "Linting completed with warnings"
        continue-on-error: true

      - name: Build project
        run: npm run build

      - name: Check bundle size
        run: |
          echo "✅ Build completed successfully!"
          ls -la dist/
          echo "📦 Bundle analysis:"
          du -sh dist/assets/* | head -10
